apiVersion: v1
kind: Pod
metadata:
  name: nome-do-pod
spec:
  containers:
    - name: nome-do-container
      image: mongo:latest
      ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Deployment
metadata:
  name: nome-do-deploy
spec:
  replicas: 1
  selector:
    matchLabel:
      chave: valor
  template:
    metadata:
      labels:
        chave: valor
    spec:
      containers:
        - name: nome-do-container
          image: mongo:latest
          ports:
            - containerPort: 27017
