---
apiVersion: v1
kind: Pod
metadata:
  name: nome-do-pod
spec:
  containers:
  - name: nome-do-container
    image: mongo
    resources:
      requests:
        cpu: 100m
        memory: 128M
      limits:
        cpu: 250m
        memory: 256M
    ports:
    - containerPort: 27017
