apiVersion: v1
kind: Pod
metadata:
  name: api-pod
spec:
  containers:
    - name: simple-api
      image: josecarlosnf/simple-node-api
      env:
        - name: PORT
          value: "8080"
      ports:
      - containerPort: 8080