apiVersion: v1
kind: Pod
metadata:
  name: simple-node-api-pod
  labels:
    app: simple-node-api-label
spec:
  containers:
  - name: simple-node-api-container
    image: josecarlosnf/simple-node-api
    env:
      - name: PORT
        value: "8080"
    ports:
      - containerPort: 8080