apiVersion: v1
kind: Secret
metadata:
  name: nome-do-secret
type: Opaque
data:
  # Dados devem ser criptografados em base64
  username: dXN1YXJpb3NlZ3Vyb3BhcmFhcGxpY2FjYW8K # usuarioseguroparaaplicacao
  password: c2VuaGFzZWd1cmFwYXJhYXBsaWNhY2FvCg== # senhaseguraparaaplicacao
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-com-secret-volume
spec:
  containers:
    - name: container-com-secret
      image: josecarlosnf/simple-node-api
      volumeMounts:
        - name: volume-com-secret
          mountPath: /mnt
          readOnly: true
  volumes:
    - name: volume-com-secret
      secret: { secretName: nome-do-secret }
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-com-secret-env
spec:
  containers:
    - name: container-com-secret
      image: josecarlosnf/simple-node-api
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: nome-do-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nome-do-secret
              key: password
